src/InventoryBundle/Entity/Store.php
<?php

namespace InventoryBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="InventoryBundle\Repository\InventoryRepository")
 * @ORM\Table(name="store")
 */
class Store
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="store_name", type="string", nullable=false)
     */
    private $storeName;

    /**
     * @var string
     *
     * @ORM\Column(name="location", type="string", nullable=false)
     */
    private $location;

    /**
     * @var string
     *
     * @ORM\Column(name="manager", type="string", nullable=false)
     */
    private $manager;

    /**
     * @var string
     *
     * @ORM\Column(name="phone_number", type="string", nullable=false)
     */
    private $phoneNumber;

    /**
     * @ORM\OneToMany(targetEntity="InventoryBundle\Entity\StoreStock", mappedBy="store")
     */
    private $storeStock;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     *
     * @return Store
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStoreName()
    {
        return $this->storeName;
    }

    /**
     * @param mixed $storeName
     *
     * @return Store
     */
    public function setStoreName($storeName)
    {
        $this->storeName = $storeName;
    }

    /**
     * @return mixed
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param mixed $location
     *
     * @return Store
     */
    public function setLocation($location)
    {
        $this->location = $location;
    }

    /**
     * @return mixed
     */
    public function getManager()
    {
        return $this->manager;
    }

    /**
     * @param mixed $manager
     *
     * @return Store
     */
    public function setManager($manager)
    {
        $this->manager = $manager;
    }

    /**
     * @return mixed
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * @param mixed $phoneNumber
     *
     * @return Store
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * @return mixed
     */
    public function getStoreStock()
    {
        return $this->storeStock;
    }

    /**
     * @param mixed $storeStock
     */
    public function setStoreStock($storeStock)
    {
        $this->storeStock = $storeStock;
    }

    /**
     * @return int
     */
    public function getStoresPrice()
    {
        $price = 0;

        if (!empty($this->storeStock) && $this->storeStock->count() > 0) {
            foreach ($this->storeStock as $storeStock) {
                $price += $storeStock->getPrice();
            }
            $price = $price / 100;
        }
        return $price;
    }


}

src/InventoryBundle/Controller/ReportController.php
<?php

namespace InventoryBundle\Controller;

use InventoryBundle\Entity\Store;
use InventoryBundle\Entity\StoreStock;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class ReportController extends Controller
{
    /**
     * @Route("/report", name="report")
     */
    public function storeTransactionAction()
    {
        $storeService = $this->get('service.store');
        $stores = $storeService->getAllStores();
        dump($stores);







        return $this->render("@Inventory/Report/report.html.twig", [
            'stores' => $stores,
        ]);
    }
}

src/InventoryBundle/Resources/views/Report/report.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container">

        {% for msg in app.session.flashBag.get('danger') %}
            <div class="alert alert-danger" role="alert">
                {{ msg }}
            </div>
        {% endfor %}
        <div class="row">

            <span class="col-md-3">

                <form class="form-inline" method="post" id="store-form">
                    <select name="store_id_from_frontend_form" class="form-control" id="store-selection">
                        <option value="">Select Store</option>
                        {% for store in stores %}

                            <option value="{{ store.id }}" selected="selected">{{ store.storeName }}</option>

                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </span>
            <span class="col-md-9">
                <div id="report-container"></div>

            </span>
            <table>
                <thead>
                    <tr>
                        <th>Grand Totals</th>

                    </tr>
                </thead>
                <tbody>
                {% for store in stores %}
                <tr>
                    <td>{{ store.storeName }}</td>
                    <td>${{ store.storesPrice | number_format(2) }}</td>
                {% endfor %}
                </tr>
                </tbody>
            </table>

        </div>
    </div>


    <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{{ asset('js/store.stock.js') }}"></script>

{% endblock content %}